{"name": "test_get_kba_classification", "status": "broken", "statusDetails": {"message": "AttributeError: module 'PytestFramework.conf.urls' has no attribute 'Knowledge_Base_Classificatio'", "trace": "def test_get_kba_classification():\n        # setup\n>       url = urls.base_url + urls.Knowledge_Base_Classificatio\nE       AttributeError: module 'PytestFramework.conf.urls' has no attribute 'Knowledge_Base_Classificatio'\n\nPytestTests\\test_TC_002_getKbaCategories.py:26: AttributeError"}, "start": 1652329364125, "stop": 1652329364125, "uuid": "e499a791-af48-42dc-b434-ccb8470085c1", "historyId": "bc6a68886608ad53dea2f08b6fcdbd22", "testCaseId": "64430001a10c64ec9ba449e05d6f47da", "fullName": "PytestTests.test_TC_002_getKbaCategories#test_get_kba_classification", "labels": [{"name": "parentSuite", "value": "PytestTests"}, {"name": "suite", "value": "test_TC_002_getKbaCategories"}, {"name": "host", "value": "INDPratap01"}, {"name": "thread", "value": "7536-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "PytestTests.test_TC_002_getKbaCategories"}]}